service: redirector
runtime: python39

env: standard
instance_class: F1

default_expiration: "14d"

automatic_scaling:
  target_cpu_utilization: 0.80
  target_throughput_utilization: 0.70
  min_idle_instances: 0
  max_idle_instances: 1
  min_instances: 0
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 60

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: .*
  script: main.app
env_variables:
  TO_REDIRECT: 'https://pistatium.dev'
